asciidoc: 
  attributes: 
    page-help-url: https://teams.microsoft.com/l/channel/19%3ae23779254c244d358a58dc03de748cfb%40thread.skype/Documentation?groupId=f3d3a37e-0fdb-4e4b-bb64-9a22e0ee3c13&tenantId=c5263ca1-a2e1-42fd-81bb-effcd1666efd
site:
  title: SSAT Digital Services Technical Guides
  start_page: docmetatech::index.adoc 
content:
  sources: 
  - url: https://github.com/ssatuk/docs.src.documentation.git
    branches: master
    start_path: tech
  - url: https://github.com/ssatuk/docs.src.learn.git
    branches: master
    start_path: tech
  - url: https://github.com/ssatuk/terraform-do-learn.git
    branches: master
    start_path: docs
  - url:  https://ssatgitbot:tb4wBa5mZ9ScLcrrzXt6@bitbucket.org/ssat/ssat.web.master.git
    branches: docs
    start_path: docs/tech
  - url:  https://ssatgitbot:tb4wBa5mZ9ScLcrrzXt6@bitbucket.org/ssat/ssat.flows.team.git
    branches: master
    start_path: docs/tech
  - url: git@github.com:ssatuk/docs.src.processes.git
    branches: master
    start_path: tech
  - url:  git@github.com:ssatuk/Xrm2Xero.git
    branches: master
    start_path: doc/tech
  - url: https://ssatgitbot:tb4wBa5mZ9ScLcrrzXt6@bitbucket.org/ssat/ssat.xrm.apps.tm.git
    branches: master
    start_path: docs/tech
  - url: git@github.com:ssatuk/docs.src.bi.git
    branches: master
    start_path: tech
  - url: git@github.com:ssatuk/SSAT.EAI.MarketingAutomation.git
    branches: master
    start_path: doc/tech
  #- url: https://gitlab.com/antora/demo/demo-component-a.git
  #  branches: master
  #- url: https://gitlab.com/antora/demo/demo-component-b.git
  #  branches: [v2.0, v1.0]
  #  start_path: docs
ui: 
  bundle:
    url: https://ssatdocsitebuilds.blob.core.windows.net/antora-ui-ssat/ui-bundle.zip
    snapshot: true