asciidoc: 
  attributes: 
    page-help-url: https://teams.microsoft.com/l/channel/19%3ae23779254c244d358a58dc03de748cfb%40thread.skype/Documentation?groupId=f3d3a37e-0fdb-4e4b-bb64-9a22e0ee3c13&tenantId=c5263ca1-a2e1-42fd-81bb-effcd1666efd
site:
  title: SSAT Digital Services Technical Guides
  start_page: docmetatech::index.adoc 
content:
  sources: 
  - url: ./workspace/docmetatech
    branches: HEAD
    start_path: tech

  - url: ./workspace/learn
    branches: HEAD
    start_path: tech

  - url: ./workspace/learn-tf
    branches: HEAD
    start_path: docs

  - url: ./workspace/web
    branches: HEAD
    start_path: docs/tech
    
  - url: ./workspace/flows
    branches: HEAD
    start_path: docs/tech

  - url: ./workspace/processes
    branches: HEAD
    start_path: tech

ui: 
  bundle:
    url: https://ssatdocsitebuilds.blob.core.windows.net/antora-ui-ssat/ui-bundle.zip
    snapshot: true